# -*- coding: utf-8 -*-
"""Group2_Iran&Oil.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ap5G9rY_Wls5Vzac3uJTS2ahgk7K36wR

## Group 2 ML Project: Predicting Oil Price in light of the Iran war
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import RandomForestRegressor,RandomForestClassifier
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error, classification_report, recall_score,accuracy_score, precision_score, f1_score,confusion_matrix

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

from sklearn.pipeline import Pipeline
from sklearn.linear_model import Ridge

from sklearn.model_selection import train_test_split

df = pd.read_excel('/content/Merged.xlsx')
display(df.head())

print("Dataset Info:")
print(df.info())

print("\nSummary Statistics:")
display(df.describe())

print("\nMissing Values per Column:")
display(df.isnull().sum())

"""We had to merge all data into weekly intervals to be able to unify and predict next week average.

**ACLED Geopolitical Data:**
* **WEEK (acled):** Starting date of aggregated geopolitical weekly events.
* **Total_Events:** Sum of Battles, Explosions, and Strategic events for the week.
* **Fatalities:** Count of fatalities.
* **Battles_Events, Explosions_Events, Strategic_Events:** Specific types of conflict event counts.
* **Country_Events (Bahrain to Yemen):** Total events recorded for each specific country; their sum equals `Total_Events`.

**GDELT Media Data:**
* **week_start, week_range(gdelt):** Date columns from the GDELT source.
* **total_geopolitical_event_volume:** Volume of events in global news.
* **average_media_sentiment:** The average tone of media coverage.
* **geopolitical_instability_score:** Calculated score for regional stability.
* **media_panic_amplification:** Measure of media focus on crisis.
* **kinetic_warfare, economic_coercion, diplomatic_threats:** Specific volumes of conflict types identified via media analysis.

**Yahoo Finance Data:**
* **start_date, end_date, date_range:** Date columns from Yahoo Finance.
* **target_brent_price:** Global benchmark for crude oil (Primary Target).
* **wti_price:** American domestic oil benchmark.
* **usd_index:** U.S. Dollar value (typically inverse to commodity prices).
* **gold_price:** Global safe-haven asset (Secondary Target).
* **defense_stocks (ITA):** ETF tracking aerospace and defense companies.
* **sp500_etf (SPY):** Broad American stock market performance.
* **energy_stocks (XLE):** ETF tracking major oil corporations.
* **oil_volatility (OVX):** 30-day expected crude oil volatility.
* **market_volatility (VIX):** Systemic risk and market 'fear' index.

**Economic & Supply Data (FRED/EIA):**
* **observation_date (waad), FEDFUNDS:** Interest rate data from the Federal Reserve.
* **Date, US_Crude_Inventories_mb:** U.S. oil reserve levels in million barrels.
* **OPEC_Production_mbpd:** OPEC crude production in million barrels per day.
"""

#we need to verify all dates from multiple data sets align then drop the repittion

user_date_cols = [
    'WEEK (acled)', 'week_start', 'week_range(gdelt)',
    'start_date (yahoo)', 'end_date', 'date_range',
    'observation_date (waad)', 'Date'
]

existing_cols = [col for col in user_date_cols if col in df.columns]

valid_date_cols = []
for col in existing_cols:
    try:
        test_val = df[col].dropna().iloc[0]
        pd.to_datetime(test_val)
        valid_date_cols.append(col)
    except (ValueError, TypeError, IndexError):
        continue

print(f"Verifying alignment using actual date columns: {valid_date_cols}")

verification_df1 = pd.DataFrame()
for col in valid_date_cols:
    verification_df1[col] = pd.to_datetime(df[col])

date_spread = (verification_df1.max(axis=1) - verification_df1.min(axis=1)).dt.days
df['date_diff_days'] = date_spread

mismatched_rows = df[df['date_diff_days'] > 7]

if mismatched_rows.empty:
    print("\ndate columns in every row are within a 7-day window.")
else:
    print(f"\nWarning: Found {len(mismatched_rows)} rows where dates span more than 7 days.")
    display(mismatched_rows[valid_date_cols + ['date_diff_days']].head())

print("\nSummary of date gaps across rows (days):")
display(df['date_diff_days'].describe())

##----


date_cols_to_drop = [
    'WEEK (acled)', 'week_start', 'week_range(gdelt)',
    'start_date (yahoo)', 'end_date', 'date_range',
    'observation_date (waad)', 'Date', 'date_diff_days'
]

df.insert(0, 'unified_week_start', pd.to_datetime(df['WEEK (acled)']))

existing_drop_list = [col for col in date_cols_to_drop if col in df.columns]
df.drop(columns=existing_drop_list, inplace=True)

df.rename(columns={'unified_week_start': 'week_start'}, inplace=True)

print("Dates unified into the 'week_start' column.")
display(df.head())

"""## We have successfully merged all dates into one column (week_start) after verifying alignment"""

# Calculate the correlation matrix
# We drop 'week_start' as it is a date and not a numeric value
corr_matrix = df.drop(columns=['week_start']).corr()

# Set up the matplotlib figure
plt.figure(figsize=(20, 15))

# Draw the heatmap
sns.heatmap(corr_matrix, annot=False, cmap='coolwarm', fmt='.2f', linewidths=0.5)

plt.title('Correlation Heatmap of All Features')
plt.show()

# Drop redundant and low-correlation features
columns_to_drop = [
    'wti_price',
    'Total_Events',
    'total_geopolitical_event_volume',
    'FEDFUNDS',
    'OPEC_Production_mbpd'
]
df.drop(columns=columns_to_drop, inplace=True)

# Merge Israel and Jordan and Palestine and Lebanon events
df['Lebanon_Palestien_Jordan_Israel_Events'] = df['Lebanon_Events'] + df['Palestine_Events'] + df['Jordan_Events'] + df['Israel_Events']
df.drop(columns=['Lebanon_Events','Palestine_Events','Jordan_Events', 'Israel_Events'], inplace=True)

# Merge Turkey and Syria events
df['Turkey_And_Syria_Events'] = df['Turkey_Events'] + df['Syria_Events']
df.drop(columns=['Turkey_Events', 'Syria_Events'], inplace=True)

print(f"New shape of dataframe: {df.shape}")
print("Remaining columns:")
display(df.columns.tolist())
display(df.head())

# More drawings to inspect data

# Histogram
plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
sns.histplot(df['target_brent_price'], kde=True, color='blue')
plt.title('Distribution of Brent Oil Price')

plt.subplot(1, 2, 2)
sns.histplot(df['gold_price'], kde=True, color='gold')
plt.title('Distribution of Gold Price')

plt.tight_layout()
plt.show()

#-----

#Time series for gold vs political instability

fig, ax1 = plt.subplots(figsize=(15, 7))

# Plotting Gold Price on the primary y-axis
ax1.set_xlabel('Week Start')
ax1.set_ylabel('Gold Price', color='orange')
ax1.plot(df['week_start'], df['gold_price'], color='orange', label='Gold Price', linewidth=2)
ax1.tick_params(axis='y', labelcolor='orange')

# Creating a secondary y-axis for Geopolitical Instability
ax2 = ax1.twinx()
ax2.set_ylabel('Instability Score', color='purple')
ax2.plot(df['week_start'], df['geopolitical_instability_score'], color='purple', linestyle='--', label='Instability Score')
ax2.tick_params(axis='y', labelcolor='purple')

plt.title('Gold Price vs. Geopolitical Instability Over Time')
fig.tight_layout()
plt.show()

"""## Now we begin classification to improve predictions: StandScaler + K-Means clustering"""

# the only goal to classify a label

war_features = [
    "Fatalities",
    "Battles_Events",
    "Explosions_Events",
    "Strategic_Events"
]

X_war = df[war_features].copy()

war_scaler = StandardScaler()
X_war_scaled = war_scaler.fit_transform(X_war)

kmeans_model = KMeans(
    n_clusters=3,
    random_state=42,
    n_init=10
)

df["War_Cluster"] = kmeans_model.fit_predict(X_war_scaled)

cluster_severity = (
    df.groupby("War_Cluster")[war_features]
       .mean()
       .sum(axis=1)
       .sort_values()
)

cluster_order = cluster_severity.index.tolist()

cluster_labels = {
    cluster_order[0]: "Low",
    cluster_order[1]: "Medium",
    cluster_order[2]: "High"
}

df["War_Intensity"] = df["War_Cluster"].map(cluster_labels)

intensity_map = {
    "Low": 0,
    "Medium": 1,
    "High": 2
}

df["War_Intensity_Code"] = (
    df["War_Intensity"].map(intensity_map)
)

df["week_start"] = pd.to_datetime(df["week_start"])

df = (
    df.sort_values("week_start")
       .reset_index(drop=True)
)

df["War_Intensity_Lag1"] = (
    df["War_Intensity_Code"].shift(1)
)

print(
    df[
        [
            "week_start",
            "War_Intensity",
            "War_Intensity_Code",
            "War_Intensity_Lag1"
        ]
    ].head(10)
)

df['Gold_Lag_1'] = df['gold_price'].shift(1)
df['Gold_Lag_2'] = df['gold_price'].shift(2)
df['Gold_Lag_4'] = df['gold_price'].shift(4)

df_gold = df.dropna(
    subset=[
        "gold_price",
        "Gold_Lag_1",
        "Gold_Lag_2",
        "Gold_Lag_4",
        "War_Intensity_Lag1"
    ]
).copy()

gold_features = [
    "Gold_Lag_1",
    "Gold_Lag_2",
    "Gold_Lag_4",
    "War_Intensity_Lag1",
    "usd_index",
    "defense_stocks",
    "sp500_etf",
    "energy_stocks",
    "oil_volatility",
    "market_volatility",
    "US_Crude_Inventories_mb"
]

X = df_gold[gold_features]
y = df_gold["gold_price"]


#splitting for time series to only look at past

split = int(len(df_gold) * 0.8)

X_train = X.iloc[:split]
X_test = X.iloc[split:]

y_train = y.iloc[:split]
y_test = y.iloc[split:]

"""## ** First Model : Gold Price with Ridge Regression**"""

model_ridge = Pipeline([
    ('scaler', StandardScaler()),
    ('ridge', Ridge(alpha=10))
])

model_ridge.fit(X_train, y_train)

y_pred_ridge = model_ridge.predict(X_test)

mae = mean_absolute_error(y_test, y_pred_ridge)
rmse = np.sqrt(mean_squared_error(y_test, y_pred_ridge))
r2 = r2_score(y_test, y_pred_ridge)

print(f"MAE  : {mae:.3f}")
print(f"RMSE : {rmse:.3f}")
print(f"R²   : {r2:.3f}")


plt.figure(figsize=(12, 5))

plt.plot(y_test.values, label='Actual')
plt.plot(y_pred_ridge, label='Predicted')

plt.title('Actual vs Predicted Gold Price - Ridge Regression')
plt.xlabel('Weeks')
plt.ylabel('Gold Price')

plt.legend()
plt.grid(True)
plt.show()

"""## ** Second Model : Oil Price with Random Forest **"""

# Feature engineering for Oil Price prediction
df['Brent_Lag_1'] = df['target_brent_price'].shift(1)
df['Brent_Lag_2'] = df['target_brent_price'].shift(2)

# Prepare features and target
oil_features = [
    "Brent_Lag_1",
    "Brent_Lag_2",
    "War_Intensity_Lag1",
    "usd_index",
    "defense_stocks",
    "sp500_etf",
    "energy_stocks",
    "oil_volatility",
    "market_volatility",
    "US_Crude_Inventories_mb"
]

# Drop rows with NaNs created by lagging
df_oil = df.dropna(subset=oil_features + ['target_brent_price']).copy()

X_oil = df_oil[oil_features]
y_oil = df_oil['target_brent_price']

# Time-series split (80/20)
split_idx = int(len(df_oil) * 0.8)
X_train_oil, X_test_oil = X_oil.iloc[:split_idx], X_oil.iloc[split_idx:]
y_train_oil, y_test_oil = y_oil.iloc[:split_idx], y_oil.iloc[split_idx:]

# Initialize and train Random Forest
rf_model = RandomForestRegressor(n_estimators=100, random_state=42)
rf_model.fit(X_train_oil, y_train_oil)

# Predictions
y_pred_rf = rf_model.predict(X_test_oil)

# Evaluation
mae_rf = mean_absolute_error(y_test_oil, y_pred_rf)
rmse_rf = np.sqrt(mean_squared_error(y_test_oil, y_pred_rf))
r2_rf = r2_score(y_test_oil, y_pred_rf)

print(f"Random Forest - Brent Oil Price Prediction")
print(f"MAE  : {mae_rf:.3f}")
print(f"RMSE : {rmse_rf:.3f}")
print(f"R²   : {r2_rf:.3f}")

# Visualization
plt.figure(figsize=(12, 5))
plt.plot(y_test_oil.values, label='Actual Brent Price', color='blue')
plt.plot(y_pred_rf, label='RF Predicted Price', color='red', linestyle='--')
plt.title('Actual vs Predicted Brent Oil Price - Random Forest')
plt.xlabel('Weeks (Test Set)')
plt.ylabel('Price')
plt.legend()
plt.grid(True)
plt.show()